project:
  type: book
  output-dir: docs

book:

  chapters:
  - index.qmd

  - part: "ODK"
    chapters:
       - LSHTM_ODK_User_Guide.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual



